apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stonewall

# Images modify the tags for images without
# creating patches.
images:
  - name: cockroachdb/cockroach
    newTag: v24.2.3

replicas:
  - name: cockroachdb
    count: 2

commonLabels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - ingress.yaml
  - job.init.yaml
  - namespace.yaml
  - poddisruptionbudget.yaml
  - service.discovery.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - statefulset.yaml
  - service.public.yaml