apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Images modify the tags for images without
# creating patches.
images:
- name: superjugger88/go
  newTag: latest

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml