apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
data:
  Caddyfile: |
    :9999 {
    handle /health {
      respond "OK"
    }
    
    }
    :80 {
      handle /api/v1/* {
        reverse_proxy api:4000
      }
    
      redir /db /db/
      handle_path /db/* {
        reverse_proxy cockroachdb:8080
      }
    
      handle {
        reverse_proxy web:3000
      }
    
      redir /mail /mail/
      handle_path /mail/* {
        reverse_proxy mailhog:8025
      }
    }
    

