apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: stonewall-env
    envs:
      - .env

resources:
  - k8s/base/db
  - k8s/base/mailhog
  - k8s/base/caddy
  - k8s/base/web
  - k8s/base/api