apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: stonewall
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: .docker/api.Dockerfile
    - image: superjugger88/nextjs
      context: .
      docker:
        dockerfile: .docker/web.Dockerfile
  local:
    useBuildkit: true
    concurrency: 2
    push: false
deploy:
  

profiles:
  - name: base
    manifests:
      kustomize:
        paths:
          - k8s/caddy/base
          - k8s/mailhog/base
          - k8s/web/base
          - k8s/api/base