apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: go-k8s
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: docker/Dockerfile.api
    - image: superjugger88/deno
      context: .
      docker:
        dockerfile: docker/Dockerfile.web
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: db
        chartPath: charts/db
        valuesFiles:
          - charts/db/values.yaml
        upgradeOnChange: false
      - name: api
        chartPath: charts/api
        valuesFiles:
          - charts/api/values.yaml
      - name: web
        chartPath: charts/web
        valuesFiles:
          - charts/web/values.yaml
      - name: mailhog
        chartPath: charts/mailhog
        valuesFiles:
          - charts/mailhog/values.yaml
        upgradeOnChange: false
      - name: caddy
        chartPath: charts/caddy
        valuesFiles:
          - charts/caddy/values.yaml
        upgradeOnChange: false