apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: stonewall
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: .docker/api.Dockerfile
    - image: superjugger88/nextjs
      context: .
      docker:
        dockerfile: .docker/web.Dockerfile
  local:
    useBuildkit: true
    concurrency: 2
    push: false
deploy:
  kubectl:
    flags:
      global:
        - --namespace=stonewall
manifests:
  kustomize:
    paths:
      - .kustomize/overlays/dev/api
      - .kustomize/overlays/dev/web
      - .kustomize/overlays/dev/mailhog
      - .kustomize/overlays/dev/db