apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: stonewall
build:
  artifacts:
    - image: superjugger88/go
      context: .
      docker:
        dockerfile: .docker/api.Dockerfile
    - image: superjugger88/nextjs
      context: .
      docker:
        dockerfile: .docker/web.Dockerfile
  local:
    useBuildkit: true
    concurrency: 2
    push: false
deploy:
  kubectl:
    {}
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev/db
      - k8s/overlays/dev/mailhog
      - k8s/overlays/dev/caddy
      - k8s/overlays/dev/web
      - k8s/overlays/dev/api