apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy
  namespace: default
data:
  Caddyfile: |
    :9999 {
    handle /health {
      respond "OK"
    }
    
    }
    :80 {
      handle /api/v1/* {
        reverse_proxy http://api:4000
      }
    
      redir /db /db/
      handle_path /db/* {
        reverse_proxy http://db-cockroachdb:8080
      }
    
      handle {
        reverse_proxy http://web:3000
      }
    
      redir /mail /mail/
      handle_path /mail/* {
        reverse_proxy http://mailhog:8025
      }
    }
    

