# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: caddy
  app.kubernetes.io/managed-by: Tiller
  app.kubernetes.io/name: caddy
  app.kubernetes.io/version: 2.8.4

# Images modify the tags for images without
# creating patches.
images:
- name: caddy
  newTag: 2.8.4-alpine

# Value of this field is prepended to the
# names of all resources
namePrefix: caddy

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- serviceaccount.yaml