FROM golang:1.21.0-alpine AS builder

WORKDIR /app

COPY stonewall-api/ .
RUN go mod download

ENV GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target="/root/.cache/go-build" go build -o main

FROM scratch

WORKDIR /srv

COPY --from=builder /app/main .

EXPOSE 8081

ENTRYPOINT ["./main"]