FROM golang:1.21.0-alpine as builder

WORKDIR /app

COPY . .
RUN go mod tidy
RUN go build -v -o main

FROM golang:1.21.0-alpine

WORKDIR /var/www

COPY --from=builder /app/main .

EXPOSE 8080

ENTRYPOINT ["./main"]