FROM denoland/deno:alpine-1.44.2

ARG GIT_REVISION
ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}

WORKDIR /app

COPY stonewall-web .
RUN deno cache main.ts \
    && deno task build

USER deno

EXPOSE 8000

CMD ["run", "-A", "main.ts"]