FROM denoland/deno:alpine-1.44.2

ARG GIT_REVISION
ENV DENO_DEPLOYMENT_ID=${GIT_REVISION}

WORKDIR /app

COPY stonewall-web .
RUN deno cache main.ts

RUN --mount=type=cache,target=/deno-dir \
    deno task build

EXPOSE 8000

CMD ["run", "-A", "main.ts"]