apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stonewall

commonLabels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - namespace.yaml