kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: cockroachdb-budget
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
      app.kubernetes.io/instance: cockroachdb
  maxUnavailable: 1
