apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Images modify the tags for images without
# creating patches.
images:
- name: docker.io/mailhog/mailhog
  newTag: v1.0.1

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml