apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- count: 1
  name: web

# Images modify the tags for images without
# creating patches.
images:
- name: superjugger88/nextjs
  newTag: latest

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ../../../base/web
- ingress.yaml
