apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - job.init.yaml
  - poddisruptionbudget.yaml
  - service.discovery.yaml
  - service.public.yaml
  - serviceaccount.yaml
  - statefulset.yaml