apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Images modify the tags for images without
# creating patches.
images:
  - name: cockroachdb/cockroach
    newTag: v24.2.3

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - job.init.yaml
  - poddisruptionbudget.yaml
  - service.discovery.yaml
  - service.public.yaml
  - serviceaccount.yaml
  - statefulset.yaml