apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cockroachdb-prometheus
  namespace: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      path: /_status/vars
      port: http
  namespaceSelector:
    matchNames:
      - stonewall
  selector:
    matchLabels:
      app.kubernetes.io/component: cockroachdb