apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: web
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: web
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: web
        app.kubernetes.io/version: 1.16.0
    spec:
      containers:
      - image: superjugger88/nextjs
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      securityContext:
        fsGroup: 1000
      serviceAccountName: web
