apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: caddy
    app.kubernetes.io/name: caddy
  type: LoadBalancer
