FROM golang:1.21.0-alpine as builder

WORKDIR /app

COPY backend/* ./

RUN go mod tidy
RUN go build -v -o cmd/main

FROM golang:1.21.0-alpine

WORKDIR /app

COPY --from=builder /app/cmd/main .

EXPOSE 80

ENTRYPOINT ["./main"]