apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
  - name: api
    count: 1

# Images modify the tags for images without
# creating patches.
images:
  - name: superjugger88/go
    newTag: latest

# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
  - ../../../base/api
  - ingress.yaml
  - configmap.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: api